### PR TITLE
[#278] Include subscriber data in /api/v1/subscriptions

### PR DESCRIPTION
**Pull request by grekko**
**Trello-Ticket**: https://trello.com/c/E1oJTeWA

### CODE REVIEW

**Comment by grekko** [comment]
@angelikatyborska jfyi: I accidentally introduced a typo which created an `avatar-url` with an obsolete `&cop=faces` query param. I removed this again 65d2e4a

**Comment by angelikatyborska** [comment]
One more question, why did you prepend the commits with `[lord#278]`? does that mean anything? I would expect just `[#278]`.

**Comment by grekko** [comment]
> One more question, why did you prepend the commits with [lord#278]? 

Yeahh.. erm thats really weird!

The git commit actually just contains `[#278] Include subscriber data in /api/v1/subscriptions`

```diff
commit 2e032831d034b6d543e4762637e634c536c2ec54
Author: Gregory Igelmund <gregory@steadyhq.com>
Date:   Mon Apr 1 22:39:55 2019 +0200

    [#278] Include subscriber data in /api/v1/subscriptions

diff --git a/source/includes/_subscriptions.md b/source/includes/_subscriptions.md
index 74c4365..3685c8f 100644
--- a/source/includes/_subscriptions.md
+++ b/source/includes/_subscriptions.md
@@ -39,7 +39,11 @@ Content-Type: application/vnd.api+json; charset=utf-8
         "subscriber": {
           "data": {
             "type": "user",
-            "id": "ffc41bfd-871b-4376-8e02-8729c752b2af"
+            "id": "ffc41bfd-871b-4376-8e02-8729c752b2af",
+            "email": "alice@example.com",
+            "first-name": "Alice",
+            "last-name": "Munro",
+            "avatar-url": "https://steady.imgix.net/gfx/some-path/avatar.svg?auto=format&cop=faces&crop=faces&fit=crop&fm=png&h=200&mask=ellipse&w=200"
           }
         }
       }
@@ -128,7 +132,11 @@ Content-Type: application/vnd.api+json; charset=utf-8
       "subscriber": {
         "data": {
           "type": "user",
-          "id": "ffc41bfd-871b-4376-8e02-8729c752b2af"
+          "id": "ffc41bfd-871b-4376-8e02-8729c752b2af",
+          "email": "alice@example.com",
+          "first-name": "Alice",
+          "last-name": "Munro",
+          "avatar-url": "https://steady.imgix.net/gfx/some-path/avatar.svg?auto=format&cop=faces&crop=faces&fit=crop&fm=png&h=200&mask=ellipse&w=200"
         }
       }
     },
```

… but github seems to do something special w/ the keyword `#123` (which usually references either a PR or an issue on the same repo).

Maybe because this a fork of Slate?

**Comment by angelikatyborska** [comment]
Looks like you're right. Github does exactly the same for commits in our non-fork repos, as can be seen here https://github.com/steady-media/main_app/pull/276/commits (number in commit mesage links to a totally unrelated PR).

**Pull request merged**
